version: "3.4"

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile-app
    environment:
      DB_HOST: database
      DB_USERNAME: root
    volumes:
      - .:/srv/christmas-queue

  assets:
    build:
      context: ./docker
      dockerfile: Dockerfile-assets
    volumes:
      - .:/srv/christmas-queue

  database:
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: christmas_queue

  proxy:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/srv/christmas-queue
    ports:
      - "8080:80"

volumes:
  database:
